apiVersion: odf.openshift.io/v1alpha1
kind: StorageSystem
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  namespace: openshift-storage
  name: ocs-storagecluster
  kind: storagecluster.ocs.openshift.io/v1
  spec:
    storageClassName: localblock
    managedResources:
      cephCluster:
        reconcileStrategy: "ignore"
    resources:
      mon:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "1"
          memory: "2Gi"
      mgr:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "1"
          memory: "2Gi"
      osd:
        requests:
          cpu: "1"
          memory: "2Gi"
        limits:
          cpu: "2"
          memory: "4Gi"
      mds:
        requests:
          cpu: "500m"
          memory: "2Gi"
        limits:
          cpu: "1"
          memory: "4Gi"
    storageDeviceSets:
    - name: ocs-deviceset
      count: 3
      replica: 2 # Using 2 replicas for testing
      dataPVCTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
          storageClassName: localblock
          volumeMode: Block
      resources:
        requests:
          cpu: "1"
          memory: "2Gi"
        limits:
          cpu: "2"
          memory: "4Gi"
    cephConfig:
      global:
        osd_heartbeat_grace: 60
        osd_heartbeat_interval: 10
        osd_op_complaint_time: 60
        mon_osd_down_out_interval: 600
        osd_recovery_max_active: 1
        osd_max_backfills: 1
        bluestore_compression_mode: none
      osd:
        osd_memory_target: 2147483648 # 2GB
